<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Coverage Report Path
    |--------------------------------------------------------------------------
    |
    | Path to the clover.xml coverage report generated by PHPUnit.
    | This can be an absolute path or relative to the project root.
    |
    */

    'clover_dir' => env('COVERAGE_CLOVER_DIR', get_modularity_vendor_path()),

    /*
    |--------------------------------------------------------------------------
    | Coverage Report Name
    |--------------------------------------------------------------------------
    |
    | Path to the clover.xml coverage report generated by PHPUnit.
    | This can be an absolute path or relative to the project root.
    |
    */

    'clover_name' => env('COVERAGE_CLOVER_NAME', 'coverage-clover.xml'),

    /*
    |--------------------------------------------------------------------------
    | Coverage Threshold
    |--------------------------------------------------------------------------
    |
    | Minimum coverage percentage required. Methods below this threshold
    | will be reported as needing attention.
    |
    | Set to 0.0 to report only completely uncovered methods.
    |
    */

    'threshold' => env('COVERAGE_THRESHOLD', 0.0),

    /*
    |--------------------------------------------------------------------------
    | Skip Magic Methods
    |--------------------------------------------------------------------------
    |
    | Whether to skip magic methods (__construct, __toString, etc.) when
    | analyzing coverage. These are typically tested indirectly.
    |
    */

    'skip_magic_methods' => env('COVERAGE_SKIP_MAGIC', true),

    /*
    |--------------------------------------------------------------------------
    | Skip Private Methods
    |--------------------------------------------------------------------------
    |
    | Whether to skip private methods when analyzing coverage.
    | Private methods are often implementation details.
    |
    */

    'skip_private_methods' => env('COVERAGE_SKIP_PRIVATE', false),

    /*
    |--------------------------------------------------------------------------
    | Skip Protected Methods
    |--------------------------------------------------------------------------
    |
    | Whether to skip protected methods when analyzing coverage.
    |
    */

    'skip_protected_methods' => env('COVERAGE_SKIP_PROTECTED', false),

    /*
    |--------------------------------------------------------------------------
    | Git Base Branch
    |--------------------------------------------------------------------------
    |
    | Default base branch for git diff comparisons when analyzing
    | changed files in pull requests.
    |
    */

    'git_base_branch' => env('COVERAGE_GIT_BASE', 'main'),

    /*
    |--------------------------------------------------------------------------
    | Output Directory
    |--------------------------------------------------------------------------
    |
    | Directory where coverage reports should be saved.
    |
    */

    'output_dir' => env('COVERAGE_OUTPUT_DIR', storage_path('app/coverage')),

    /*
    |--------------------------------------------------------------------------
    | Report Formats
    |--------------------------------------------------------------------------
    |
    | Available report formats: json, markdown, html
    |
    */

    'report_formats' => [
        'json' => true,
        'markdown' => true,
        'html' => true,
    ],

    /*
    |--------------------------------------------------------------------------
    | File Filters
    |--------------------------------------------------------------------------
    |
    | Paths or patterns to include/exclude when analyzing coverage.
    |
    */

    'filters' => [
        'include' => [
            'src/',
            'app/',
        ],
        'exclude' => [
            'tests/',
            'vendor/',
            'config/',
            'database/migrations/',
        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | PR Check Settings
    |--------------------------------------------------------------------------
    |
    | Configuration for automated PR coverage checks.
    |
    */

    'pr_check' => [
        'enabled' => env('COVERAGE_PR_CHECK_ENABLED', true),
        'fail_on_uncovered' => env('COVERAGE_PR_CHECK_FAIL', false),
        'comment_on_pr' => env('COVERAGE_PR_CHECK_COMMENT', true),
    ],

    'gemini_api_key' => env('MODULARITY_COVERAGE_GEMINI_API_KEY'),
    'anthropic_api_key' => env('MODULARITY_COVERAGE_ANTHROPIC_API_KEY'),
    'openai_api_key' => env('MODULARITY_COVERAGE_OPENAI_API_KEY'),
    'ollama_endpoint' => env('MODULARITY_COVERAGE_OLLAMA_ENDPOINT', 'http://localhost:11434'),

];
